# Test-Requests für VS Code
# Erfordert Extension REST Client

POST http://localhost:5001/api/movies
content-type: application/json

{
    "id": "1",
    "title": "The Imitation Game",
    "year": "2014",
    "summary": "Das wahre Rätsel war der Mann, der den Code knackte",
    "actors": ["Benedict Cumberbatch", "Keira Knightley"]
}

###
POST http://localhost:5001/api/movies
content-type: application/json

{
    "id": "2",
    "title": "Top Gun: Maverick",
    "year": "2022",
    "summary": "Spüre das Bedürfnis... Das Bedürfnis nach Geschwindigkeit.",
    "actors": ["Tom Cruise", "Miles Teller", "Jenniver Connelly"]
}

###
GET http://localhost:5001/api/movies

###
GET http://localhost:5001/api/movies/1

###
GET http://localhost:5001/api/movies/2

###
DELETE http://localhost:5001/api/movies/1

###
DELETE http://localhost:5001/api/movies/2

###
GET http://localhost:5001/check